[project]
name = "ai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faiss-cpu",
    "google-generativeai",
    "huggingface-hub",
    "langchain==0.3.25",
    "langchain-community==0.3.24",
    "langchain-core==0.3.59",
    "langchain-google-genai",
    "langchain-text-splitters",
    "pypdf2",
    "python-dotenv",
    "sentence-transformers",
    "streamlit",
    "torch",
    "transformers",
]
